# Generated by Django 2.0.3 on 2018-03-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.ManyToManyField(help_text='Select', to='teacher.Students'),
        ),
    ]
